# Generated by Django 5.2.6 on 2025-11-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="parsed_requirements",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
