# Generated by Django 5.2.6 on 2025-11-05 20:57

from django.conf import settings
from django.db import migrations, models


def normalize_statuses(apps, schema_editor):
    TailoringSession = apps.get_model("tailoring", "TailoringSession")
    mappings = {
        "pending": "PENDING",
        "processing": "PROCESSING",
        "completed": "COMPLETED",
        "failed": "FAILED",
    }
    for old_value, new_value in mappings.items():
        TailoringSession.objects.filter(status=old_value).update(status=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_jobposting_metadata_jobposting_parsed_requirements_and_more"),
        ("tailoring", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tailoringsession",
            name="ai_suggestions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tailoringsession",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tailoringsession",
            name="cover_letter",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tailoringsession",
            name="debug_log",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tailoringsession",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tailoringsession",
            name="generated_sections",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="tailoringsession",
            name="job_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tailoringsession",
            name="openai_run_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="tailoringsession",
            name="parameters",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tailoringsession",
            name="tailored_resume",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tailoringsession",
            name="token_usage",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="tailoringsession",
            name="generated_bullets",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="tailoringsession",
            name="input_experience_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(normalize_statuses, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="tailoringsession",
            index=models.Index(
                fields=["status", "created_at"], name="tailoring_t_status_cd4078_idx"
            ),
        ),
    ]
