# Generated by Django 4.2.26 on 2025-11-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tailoring", "0002_tailoringsession_ai_suggestions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tailoringsession",
            name="output_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
