# Generated by Django 5.2.6 on 2025-11-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="words_used",
            field=models.IntegerField(default=0),
        ),
    ]
