# Generated by Django 4.2.26 on 2025-11-06 00:57

from django.db import migrations


def seed_admin_tokens(apps, schema_editor):
    """
    Update admin user to have 100,000 tokens and all new users to have 10,000 tokens.
    """
    User = apps.get_model('accounts', 'User')
    
    # Update admin user if exists
    admin_users = User.objects.filter(username='admin')
    if admin_users.exists():
        admin_users.update(token_quota=100000)
        print("✓ Updated admin user to 100,000 tokens")
    
    # Update all superusers to have 100k tokens
    User.objects.filter(is_superuser=True).update(token_quota=100000)
    
    # Update regular users who still have old 1000 token quota to new 10000 default
    User.objects.filter(token_quota=1000, is_superuser=False).update(token_quota=10000)
    print("✓ Updated regular users to 10,000 tokens")


def reverse_seed_admin_tokens(apps, schema_editor):
    """
    Reverse migration - restore to old values if needed.
    """
    User = apps.get_model('accounts', 'User')
    # Don't actually reverse this - we want to keep the higher quotas
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_words_used"),
    ]

    operations = [
        migrations.RunPython(seed_admin_tokens, reverse_seed_admin_tokens),
    ]
