# Generated by Django 4.2.26 on 2025-11-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_seed_admin_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token_quota",
            field=models.IntegerField(default=10000),
        ),
    ]
